#!/bin/bash

# Notifies the user when the battery falls below an amount

charge="$(cat /sys/class/power_supply/BAT1/capacity)"
warning=15

if [ $charge -lt $warning ]; then
    notify-send "Low battery!"
    mpv --really-quiet ~/.config/dunst/notify.opus
fi

